export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
export const UPDATE_QTY_ADDRESS = 'UPDATE_QTY_ADDRESS';
export const SET_ADDRESS_ERROR = 'SET_ADDRESS_ERROR';
